import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import WaveformPlayer from "./WaveformPlayer";

type Route = "library" | "projects" | "safety";
type IconName = "shield"|"folder"|"folderOpen"|"plus"|"refresh"|"search"|"filter"|"grid"|"settings"|"play"|"star"|"more"|"chevron"|"music"|"brain"|"drag"|"copy"|"external"|"database"|"project"|"safe"|"reset";
const iconPaths:Record<IconName,React.ReactNode>={
  shield:<><path d="M12 3 5 6v5c0 4.6 2.8 8 7 10 4.2-2 7-5.4 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-5"/></>,
  folder:<path d="M3 6.5h6l2 2h10v10.5H3Z"/>,folderOpen:<><path d="M3 7h6l2 2h10v2"/><path d="m4 19 2-8h16l-2 8Z"/></>,plus:<><path d="M12 5v14M5 12h14"/></>,
  refresh:<><path d="M20 7v5h-5"/><path d="M19 12a7 7 0 1 0-2 5"/></>,search:<><circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/></>,
  filter:<><path d="M4 6h16M7 12h10M10 18h4"/></>,grid:<><rect x="4" y="4" width="6" height="6"/><rect x="14" y="4" width="6" height="6"/><rect x="4" y="14" width="6" height="6"/><rect x="14" y="14" width="6" height="6"/></>,
  settings:<><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1a8 8 0 0 0-1.7-1L14.5 3h-5l-.4 3a8 8 0 0 0-1.7 1L5 6.1 3 9.5 5.1 11a7 7 0 0 0 0 2L3 14.5 5 18l2.4-1a8 8 0 0 0 1.7 1l.4 3h5l.4-3a8 8 0 0 0 1.7-1l2.4 1 2-3.5-2.1-1.5a7 7 0 0 0 .1-1Z"/></>,
  play:<path d="m9 6 9 6-9 6Z"/>,star:<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z"/>,more:<><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>,
  chevron:<path d="m9 6 6 6-6 6"/>,music:<><path d="M9 18V5l10-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="16" cy="16" r="3"/></>,brain:<><path d="M9 5a3 3 0 0 0-5 2 3 3 0 0 0 0 5 3 3 0 0 0 3 5h2M15 5a3 3 0 0 1 5 2 3 3 0 0 1 0 5 3 3 0 0 1-3 5h-2M9 3v18M15 3v18"/></>,
  drag:<><path d="M8 5h8M8 12h8M8 19h8"/><circle cx="5" cy="5" r="1" fill="currentColor"/><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="5" cy="19" r="1" fill="currentColor"/></>,copy:<><rect x="8" y="8" width="11" height="12" rx="2"/><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h2"/></>,external:<><path d="M14 4h6v6M20 4l-9 9"/><path d="M18 13v6H5V6h6"/></>,database:<><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 11v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6"/></>,project:<><path d="M5 4h6l2 3h6v13H5Z"/></>,safe:<><circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/></>,reset:<><path d="M4 8V4h4M4.5 4.5A9 9 0 1 1 3 14"/></>
};
function Icon({name,size=18}:{name:IconName;size?:number}){return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{iconPaths[name]}</svg>}
const formatBytes=(value=0)=>{const units=["B","KB","MB","GB","TB"];let n=value,index=0;while(n>=1024&&index<units.length-1){n/=1024;index+=1;}return `${n.toFixed(index?1:0)} ${units[index]}`};
const formatDuration=(ms?:number)=>ms?`${(ms/1000).toFixed(ms<10000?2:1)}s`:"—";
const sourceLabel=(value?:string)=>value==="embedded_metadata"?"metadata file":value==="filename"?"tên file":"chưa xác minh";
function Badge({children,tone="neutral"}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}

interface WorkspaceLayout{sidebar:number;detail:number;memory:number;columns:number[]}
const defaultLayout:WorkspaceLayout={sidebar:296,detail:380,memory:316,columns:[360,78,230,88,84,152,86]};
function readLayout():WorkspaceLayout{try{return {...defaultLayout,...JSON.parse(localStorage.getItem("mh-layout-v2")||"{}")}}catch{return defaultLayout}}
function useLayout(){const [layout,setLayout]=useState<WorkspaceLayout>(readLayout);useEffect(()=>localStorage.setItem("mh-layout-v2",JSON.stringify(layout)),[layout]);return {layout,setLayout,reset:()=>setLayout(defaultLayout)}}

function beginResize(event:React.PointerEvent,onMove:(deltaX:number,deltaY:number)=>void){
  event.preventDefault();const startX=event.clientX,startY=event.clientY;const move=(next:PointerEvent)=>onMove(next.clientX-startX,next.clientY-startY);const stop=()=>{document.removeEventListener("pointermove",move);document.removeEventListener("pointerup",stop);document.body.classList.remove("resizing")};document.body.classList.add("resizing");document.addEventListener("pointermove",move);document.addEventListener("pointerup",stop,{once:true});
}

export default function App(){
  const [boot,setBoot]=useState<Bootstrap|null>(null);const [roots,setRoots]=useState<LibraryRoot[]>([]);const [trees,setTrees]=useState<Record<number,LibraryFolder[]>>({});const [projects,setProjects]=useState<Project[]>([]);
  const [samples,setSamples]=useState<Sample[]>([]);const [selected,setSelected]=useState<Sample|null>(null);const [selectedRoot,setSelectedRoot]=useState<number|undefined>();const [selectedFolder,setSelectedFolder]=useState<number|undefined>();
  const [query,setQuery]=useState("");const [extension,setExtension]=useState("");const [favoriteOnly,setFavoriteOnly]=useState(false);const [sort,setSort]=useState("context");const [route,setRoute]=useState<Route>("library");
  const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [progress,setProgress]=useState<Record<number,ScanProgress>>({});const [autoplayToken,setAutoplayToken]=useState(0);
  const [currentProjectId,setCurrentProjectId]=useState<number|undefined>();const [duplicates,setDuplicates]=useState<DuplicateGroup[]>([]);const [settingsOpen,setSettingsOpen]=useState(false);const [projectName,setProjectName]=useState("");
  const {layout,setLayout,reset}=useLayout();const searchSequence=useRef(0);

  const refreshTree=useCallback(async(rootId:number)=>{const tree=await window.mh.library.tree(rootId);setTrees(current=>({...current,[rootId]:tree}));},[]);
  const refreshBootstrap=useCallback(async()=>{const data=await window.mh.app.bootstrap();setBoot(data);setRoots(data.roots);setProjects(data.projects);if(!currentProjectId&&data.projects[0])setCurrentProjectId(data.projects[0].id);await Promise.all(data.roots.map(root=>refreshTree(root.id)));},[currentProjectId,refreshTree]);
  const runSearch=useCallback(async()=>{const sequence=++searchSequence.current;setLoading(true);try{const rows=await window.mh.samples.search({query,rootId:selectedRoot,folderId:selectedFolder,extension:extension||undefined,favorite:favoriteOnly,sort,available:"available",limit:1000});if(sequence!==searchSequence.current)return;setSamples(rows);if(selected&&!rows.some(item=>item.id===selected.id))setSelected(null);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Không tìm kiếm được thư viện.");}finally{if(sequence===searchSequence.current)setLoading(false)}},[query,selectedRoot,selectedFolder,extension,favoriteOnly,sort,selected?.id]);
  useEffect(()=>{refreshBootstrap().then(runSearch).catch(()=>setError("Không khởi tạo được ứng dụng."));const off=window.mh.app.onProgress((item)=>{setProgress(current=>({...current,[item.rootId]:item}));refreshTree(item.rootId).catch(()=>{});runSearch();if(["indexed","error","cancelled"].includes(item.status))refreshBootstrap().catch(()=>{});});return off},[]);
  useEffect(()=>{const timer=setTimeout(runSearch,160);return()=>clearTimeout(timer)},[query,selectedRoot,selectedFolder,extension,favoriteOnly,sort]);
  useEffect(()=>{if(route==="safety")window.mh.safety.duplicates().then(setDuplicates).catch(()=>setError("Không tải được báo cáo trùng lặp."))},[route]);

  const stats=boot?.stats||{total:0,available:0,missing:0,size_bytes:0};const selectedProject=projects.find(project=>project.id===currentProjectId);
  const selectSample=async(id:number,play=false)=>{const detail=await window.mh.samples.get(id);setSelected(detail);if(play)setAutoplayToken(Date.now())};
  const updateSelected=async(patch:Partial<Sample>)=>{if(!selected)return;const next=await window.mh.samples.update(selected.id,patch);setSelected(next);setSamples(list=>list.map(item=>item.id===next.id?{...item,...next}:item))};
  const addFolder=async()=>{const root=await window.mh.library.addFolder();if(root){setSelectedRoot(root.id);setSelectedFolder(undefined);setNotice(`Đang phát hiện cây thư mục “${root.display_name}”…`);await refreshBootstrap()}};
  const chooseRoot=(id?:number)=>{setSelectedRoot(id);setSelectedFolder(undefined)};
  const createProject=async()=>{if(!projectName.trim())return;const project=await window.mh.projects.create({name:projectName.trim()});setProjects(await window.mh.projects.list());setCurrentProjectId(project.id);setProjectName("");setNotice("Đã tạo Project Workspace.")};
  const confirmUsage=async()=>{if(!selected||!currentProjectId)return;await window.mh.projects.addMemory({project_id:currentProjectId,sample_id:selected.id,event_type:"user_confirmed",source:"manual_confirmation",confidence:1});setSelected(await window.mh.samples.get(selected.id));setNotice("Đã ghi nhận xác nhận của producer, không suy đoán tự động.")};
  const sidebarStart=layout.sidebar,detailStart=layout.detail,memoryStart=layout.memory;

  return <main className="app-shell" style={{"--sidebar-width":`${layout.sidebar}px`,"--detail-height":`${layout.detail}px`,"--memory-width":`${layout.memory}px`} as React.CSSProperties}>
    <CrateSidebar roots={roots} trees={trees} stats={stats} progress={progress} selectedRoot={selectedRoot} selectedFolder={selectedFolder} chooseRoot={chooseRoot} chooseFolder={(rootId,folderId)=>{setSelectedRoot(rootId);setSelectedFolder(folderId)}} addFolder={addFolder} rescan={()=>selectedRoot&&window.mh.library.rescan(selectedRoot)} route={route} setRoute={setRoute}/>
    <div className="resize-handle sidebar-resizer" role="separator" aria-label="Đổi chiều rộng Local Crate" onPointerDown={event=>beginResize(event,(dx)=>setLayout(value=>({...value,sidebar:Math.max(230,Math.min(440,sidebarStart+dx))})))}/>
    <section className="workspace">
      <header className="topbar">
        <div className="search-box"><Icon name="search" size={20}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Tìm sample, folder, pack, tag…" aria-label="Tìm sample"/>{query&&<button onClick={()=>setQuery("")} aria-label="Xóa tìm kiếm">×</button>}</div>
        <button className={favoriteOnly?"top-button active":"top-button"} onClick={()=>setFavoriteOnly(value=>!value)}><Icon name="filter"/> Bộ lọc {favoriteOnly&&<Badge tone="cyan">1</Badge>}</button>
        <select className="top-select" value={extension} onChange={event=>setExtension(event.target.value)} aria-label="Định dạng"><option value="">Mọi định dạng</option>{["wav","aif","aiff","flac","mp3","ogg","m4a"].map(item=><option key={item} value={item}>{item.toUpperCase()}</option>)}</select>
        <button className="square-button" title="Đặt lại bố cục" onClick={reset}><Icon name="reset"/></button><button className="square-button" title="Cài đặt" onClick={()=>setSettingsOpen(true)}><Icon name="settings"/></button>
      </header>
      {notice&&<button className="notice" onClick={()=>setNotice("")}>{notice}<span>×</span></button>}{error&&<div className="error-banner" role="alert">{error}<button onClick={()=>setError("")}>×</button></div>}
      {route==="library"&&<LibraryView samples={samples} selected={selected} loading={loading} onSelect={selectSample} onUpdate={updateSelected} autoplayToken={autoplayToken} currentProject={selectedProject} currentProjectId={currentProjectId} projects={projects} setCurrentProjectId={setCurrentProjectId} confirmUsage={confirmUsage} sort={sort} setSort={setSort} columns={layout.columns} setColumns={(columns)=>setLayout(value=>({...value,columns}))} detailHeight={layout.detail} setDetailHeight={(dy)=>setLayout(value=>({...value,detail:Math.max(250,Math.min(620,detailStart-dy))}))} memoryWidth={layout.memory} setMemoryWidth={(dx)=>setLayout(value=>({...value,memory:Math.max(250,Math.min(480,memoryStart-dx))}))} onNotice={setNotice}/>}
      {route==="projects"&&<ProjectsView projects={projects} currentProjectId={currentProjectId} setCurrentProjectId={setCurrentProjectId} projectName={projectName} setProjectName={setProjectName} createProject={createProject}/>}
      {route==="safety"&&<SafetyView groups={duplicates}/>}
    </section>
    <footer className="statusbar"><span><Icon name="shield" size={14}/> Local-first · file gốc chỉ đọc</span><span>{Object.values(progress).some(item=>["discovering","analyzing"].includes(item.status))?"Đang lập chỉ mục nền":"Sẵn sàng"}</span><span>MH Sample FL · Desktop alpha · VST3 khóa</span></footer>
    {settingsOpen&&<SettingsModal close={()=>setSettingsOpen(false)} setNotice={setNotice} resetLayout={reset}/>}
  </main>;
}

function CrateSidebar({roots,trees,stats,progress,selectedRoot,selectedFolder,chooseRoot,chooseFolder,addFolder,rescan,route,setRoute}:{roots:LibraryRoot[];trees:Record<number,LibraryFolder[]>;stats:Bootstrap["stats"];progress:Record<number,ScanProgress>;selectedRoot?:number;selectedFolder?:number;chooseRoot:(id?:number)=>void;chooseFolder:(rootId:number,folderId:number)=>void;addFolder:()=>void;rescan:()=>void;route:Route;setRoute:(route:Route)=>void}){
  return <aside className="sidebar"><div className="brand"><span className="brand-mark"><Icon name="shield" size={27}/></span><div><strong>MH Sample <em>FL</em></strong><small>Find · Remember · Protect</small></div></div>
    <nav className="route-tabs" aria-label="Khu vực ứng dụng"><button className={route==="library"?"active":""} onClick={()=>setRoute("library")}><Icon name="music"/>Thư viện</button><button className={route==="projects"?"active":""} onClick={()=>setRoute("projects")}><Icon name="project"/>Dự án</button><button className={route==="safety"?"active":""} onClick={()=>setRoute("safety")}><Icon name="safe"/>An toàn</button></nav>
    <div className="crate-heading"><div><b>Local Crate</b><span>Cấu trúc folder thật trên ổ đĩa</span></div><button onClick={addFolder} title="Thêm thư mục"><Icon name="plus"/></button></div>
    <div className="tree-scroll"><button className={!selectedRoot?"tree-root selected":"tree-root"} onClick={()=>chooseRoot(undefined)}><Icon name="database"/><span><b>Tất cả thư viện</b><small>{stats.available} sample khả dụng</small></span></button>
      {roots.map(root=><RootTree key={root.id} root={root} nodes={trees[root.id]||[]} progress={progress[root.id]} activeRoot={selectedRoot===root.id} selectedFolder={selectedFolder} chooseRoot={()=>chooseRoot(root.id)} chooseFolder={(id)=>chooseFolder(root.id,id)}/>)}</div>
    <div className="crate-health"><div className="health-title"><b>Tình trạng thư viện</b><span>{stats.total?Math.round(stats.available/stats.total*100):0}% khả dụng</span></div><div className="health-bar"><i style={{width:`${stats.total?stats.available/stats.total*100:0}%`}}/></div><div className="health-grid"><span><i className="status-dot indexed"/>Đã lập chỉ mục <b>{stats.available}</b></span><span><i className="status-dot missing"/>Thiếu <b>{stats.missing}</b></span><span>Dung lượng <b>{formatBytes(stats.size_bytes)}</b></span></div><button className="quiet-button" onClick={rescan} disabled={!selectedRoot}><Icon name="refresh"/> Quét lại phạm vi đang chọn</button></div>
  </aside>
}

function RootTree({root,nodes,progress,activeRoot,selectedFolder,chooseRoot,chooseFolder}:{root:LibraryRoot;nodes:LibraryFolder[];progress?:ScanProgress;activeRoot:boolean;selectedFolder?:number;chooseRoot:()=>void;chooseFolder:(id:number)=>void}){
  const [open,setOpen]=useState(true);const state=progress?.status||root.status;return <div className="tree-group"><div className={activeRoot&&!selectedFolder?"tree-root selected":"tree-root"}><button className="tree-caret" onClick={()=>setOpen(value=>!value)} aria-label={open?"Thu cây folder":"Mở cây folder"}><Icon name="chevron" size={14}/></button><button className="tree-root-main" onClick={chooseRoot}><Icon name={open?"folderOpen":"folder"}/><span><b>{root.display_name}</b><small>{progress?.discovered??root.file_count} file · {progress?.folders??nodes.length} folder</small></span><Badge tone={state==="indexed"?"success":state==="error"?"danger":"warning"}>{state==="discovering"?"Đang dò":state==="analyzing"?`${progress?.analyzed||0}/${progress?.discovered||0}`:state}</Badge></button></div>{open&&<div className="tree-children">{nodes.length?nodes.map(node=><FolderNode key={node.id} node={node} selectedFolder={selectedFolder} chooseFolder={chooseFolder}/>):state==="indexed"?<span className="tree-empty">Không có folder con</span>:<span className="tree-empty">Đang đọc cấu trúc…</span>}</div>}</div>
}
function FolderNode({node,selectedFolder,chooseFolder}:{node:LibraryFolder;selectedFolder?:number;chooseFolder:(id:number)=>void}){const [open,setOpen]=useState(node.depth<2);const hasChildren=node.children.length>0;return <div className="folder-node"><div className={selectedFolder===node.id?"folder-line selected":"folder-line"}>{hasChildren?<button className={open?"tree-caret open":"tree-caret"} onClick={()=>setOpen(value=>!value)}><Icon name="chevron" size={13}/></button>:<span className="tree-spacer"/>}<button className="folder-main" onClick={()=>chooseFolder(node.id)} title={node.path}><Icon name={open&&hasChildren?"folderOpen":"folder"} size={16}/><span>{node.name}</span><small>{node.total_sample_count}</small></button></div>{open&&hasChildren&&<div className="tree-children nested">{node.children.map(child=><FolderNode key={child.id} node={child} selectedFolder={selectedFolder} chooseFolder={chooseFolder}/>)}</div>}</div>}

function LibraryView({samples,selected,loading,onSelect,onUpdate,autoplayToken,currentProject,currentProjectId,projects,setCurrentProjectId,confirmUsage,sort,setSort,columns,setColumns,detailHeight,setDetailHeight,memoryWidth,setMemoryWidth,onNotice}:{samples:Sample[];selected:Sample|null;loading:boolean;onSelect:(id:number,play?:boolean)=>void;onUpdate:(patch:Partial<Sample>)=>void;autoplayToken:number;currentProject?:Project;currentProjectId?:number;projects:Project[];setCurrentProjectId:(id:number)=>void;confirmUsage:()=>void;sort:string;setSort:(sort:string)=>void;columns:number[];setColumns:(columns:number[])=>void;detailHeight:number;setDetailHeight:(dy:number)=>void;memoryWidth:number;setMemoryWidth:(dx:number)=>void;onNotice:(message:string)=>void}){
  const tableWidth=columns.reduce((sum,value)=>sum+value,0);const columnTemplate=columns.map(value=>`${value}px`).join(" ");
  const resizeColumn=(index:number,event:React.PointerEvent)=>{const start=columns[index];beginResize(event,(dx)=>{const next=[...columns];next[index]=Math.max(index===0?220:64,Math.min(index===0?620:360,start+dx));setColumns(next)})};
  return <div className="library-layout"><section className="results-panel"><div className="results-toolbar"><div><b>{samples.length}</b> kết quả <span>{loading?"Đang cập nhật…":"Từ dữ liệu trên máy"}</span></div><label>Sắp xếp <select value={sort} onChange={event=>setSort(event.target.value)}><option value="context">Ngữ cảnh thông minh</option><option value="name">Tên A–Z</option><option value="recent">Mới cập nhật</option><option value="usage">Dùng nhiều</option><option value="rating">Đánh giá</option></select></label></div><div className="sample-table-scroll" role="table" aria-label="Danh sách sample"><div className="sample-table" style={{width:tableWidth,minWidth:"100%"}}><div className="table-head" style={{gridTemplateColumns:columnTemplate}} role="row">{["Tên sample","Loại","Folder / Pack","BPM","Key","Lịch sử dùng","Thời lượng"].map((label,index)=><span key={label} role="columnheader">{label}<i className="column-resizer" role="separator" onPointerDown={event=>resizeColumn(index,event)}/></span>)}</div>{loading&&!samples.length&&<div className="table-state">Đang đọc chỉ mục…</div>}{!loading&&!samples.length&&<div className="table-state"><Icon name="search" size={26}/><b>Không có sample trong phạm vi này</b><span>Chọn folder khác hoặc xóa bộ lọc.</span></div>}{samples.map(sample=><SampleRow key={sample.id} sample={sample} selected={selected?.id===sample.id} template={columnTemplate} onSelect={onSelect} projectId={currentProjectId}/>)}</div></div></section>
    <div className="resize-handle detail-resizer" role="separator" aria-label="Đổi chiều cao vùng sample" onPointerDown={event=>beginResize(event,(_dx,dy)=>setDetailHeight(dy))}/>
    <div className="detail-zone"><section className="sample-inspector"><InspectorHeader sample={selected} onUpdate={onUpdate}/>{selected&&<MetadataStrip sample={selected}/>}<WaveformPlayer sample={selected} autoplayToken={autoplayToken} projectBpm={currentProject?.bpm} onNotice={onNotice}/>{selected&&<InspectorFooter sample={selected} onUpdate={onUpdate} currentProjectId={currentProjectId}/>}</section>
      <div className="resize-handle memory-resizer" role="separator" aria-label="Đổi chiều rộng Project Memory" onPointerDown={event=>beginResize(event,(dx)=>setMemoryWidth(dx))}/><ProjectMemory selected={selected} projects={projects} currentProjectId={currentProjectId} setCurrentProjectId={setCurrentProjectId} confirmUsage={confirmUsage}/></div>
  </div>
}

function SampleRow({sample,selected,template,onSelect,projectId}:{sample:Sample;selected:boolean;template:string;onSelect:(id:number,play?:boolean)=>void;projectId?:number}){return <div className={selected?"sample-row selected":"sample-row"} style={{gridTemplateColumns:template}} role="row" onClick={()=>onSelect(sample.id)} onDoubleClick={()=>onSelect(sample.id,true)} draggable={Boolean(sample.available)} onDragStart={event=>{event.preventDefault();window.mh.samples.startDrag(sample.id,projectId)}}><span className="file-cell" role="cell"><button onClick={event=>{event.stopPropagation();onSelect(sample.id,true)}} aria-label={`Nghe ${sample.filename}`}><Icon name="play" size={13}/></button><span><b>{sample.filename}</b><small>{sample.category||sample.tags?.slice(0,3).join(" · ")||"Chưa gắn tag"}</small></span>{sample.favorite?<Icon name="star" size={14}/>:null}</span><span role="cell"><Badge tone="cyan">{sample.extension.toUpperCase()}</Badge></span><span className="truncate" role="cell" title={sample.folder_relative_path||sample.root_name}>{sample.pack||sample.folder_relative_path||sample.root_name}</span><span role="cell" className="musical-value">{sample.bpm_original?Math.round(sample.bpm_original):"—"}</span><span role="cell" className="musical-value">{sample.musical_key||"—"}</span><span role="cell"><b className="usage">{sample.confirmed_usage_count}</b> xác nhận · {sample.preview_count} nghe</span><span role="cell">{formatDuration(sample.duration_ms)}</span></div>}

function InspectorHeader({sample,onUpdate}:{sample:Sample|null;onUpdate:(patch:Partial<Sample>)=>void}){return <header className="inspector-head"><div><span className="eyebrow">Sample Inspector</span><h2>{sample?.filename||"Chưa chọn sample"}</h2>{sample&&<p title={sample.path}>{sample.folder_relative_path?`${sample.root_name} / ${sample.folder_relative_path}`:sample.root_name}</p>}</div>{sample&&<div className="inspector-actions"><button className={sample.favorite?"square-button favorite":"square-button"} onClick={()=>onUpdate({favorite:sample.favorite?0:1})} title="Yêu thích"><Icon name="star"/></button><button className="action-button" onClick={()=>window.mh.samples.openFolder(sample.id)}><Icon name="external"/> Mở folder</button><button className="square-button" onClick={()=>window.mh.samples.copyPath(sample.id)} title="Copy path"><Icon name="copy"/></button></div>}</header>}
function MetadataStrip({sample}:{sample:Sample}){const confidence=Math.round(Math.max(sample.bpm_confidence||0,sample.key_confidence||0)*100);return <div className="metadata-strip"><span><small>Tempo gốc</small><b>{sample.bpm_original?`${Math.round(sample.bpm_original)} BPM`:"Chưa xác minh"}</b></span><span><small>Key gốc</small><b>{sample.musical_key||"Chưa xác minh"}</b></span><span><small>Độ tin cậy</small><b>{confidence?`${confidence}% · ${sourceLabel(sample.analysis_source)}`:"Không có dữ liệu"}</b></span><span><small>Định dạng</small><b>{sample.sample_rate?`${(sample.sample_rate/1000).toFixed(1)} kHz · `:""}{sample.bit_depth?`${sample.bit_depth}-bit · `:""}{sample.channels===1?"Mono":sample.channels===2?"Stereo":sample.codec||sample.extension.toUpperCase()}</b></span><span><small>Dung lượng</small><b>{formatBytes(sample.size_bytes)}</b></span></div>}

function InspectorFooter({sample,onUpdate,currentProjectId}:{sample:Sample;onUpdate:(patch:Partial<Sample>)=>void;currentProjectId?:number}){const [tags,setTags]=useState(sample.tags.join(", "));const [note,setNote]=useState(sample.note||"");useEffect(()=>{setTags(sample.tags.join(", "));setNote(sample.note||"")},[sample.id]);return <div className="inspector-footer"><div className="quick-fields"><label><span>Tags</span><input value={tags} onChange={event=>setTags(event.target.value)} onBlur={()=>window.mh.samples.setTags(sample.id,tags.split(","))} placeholder="kick, one-shot…"/></label><label><span>Ghi chú producer</span><input value={note} onChange={event=>setNote(event.target.value)} onBlur={()=>onUpdate({note})} placeholder="Cách sample này hoạt động trong mix…"/></label></div><div className="drag-card" draggable onDragStart={event=>{event.preventDefault();window.mh.samples.startDrag(sample.id,currentProjectId)}}><Icon name="drag" size={24}/><span><b>Kéo sample này sang FL Studio</b><small>{sample.filename} · file gốc trên máy</small></span><Badge tone="success">Sẵn sàng kéo</Badge></div></div>}

function ProjectMemory({selected,projects,currentProjectId,setCurrentProjectId,confirmUsage}:{selected:Sample|null;projects:Project[];currentProjectId?:number;setCurrentProjectId:(id:number)=>void;confirmUsage:()=>void}){return <aside className="project-memory"><header><span className="memory-icon"><Icon name="brain"/></span><div><h3>Project Memory</h3><p>Nhớ quyết định thật, không đoán usage.</p></div></header><label className="select-field"><span>Project hiện tại</span><select value={currentProjectId||""} onChange={event=>setCurrentProjectId(Number(event.target.value))}><option value="">Chưa chọn project</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name}{project.bpm?` · ${project.bpm} BPM`:""}</option>)}</select></label>{selected?.memories?.length?<div className="memory-list">{selected.memories.slice(0,5).map(memory=><article key={memory.id}><div><b>{memory.project_name}</b><Badge tone={memory.event_type==="user_confirmed"?"success":"warning"}>{memory.event_type==="user_confirmed"?"Đã xác nhận":"Đã gửi"}</Badge></div><p>{memory.role||memory.style_context||"Chưa ghi vai trò"}</p><small>{memory.source} · {Math.round(memory.confidence*100)}% · {new Date(memory.occurred_at).toLocaleDateString("vi-VN")}</small></article>)}</div>:<div className="memory-empty"><Icon name="brain" size={28}/><b>Chưa có ký ức project</b><span>Chỉ ghi khi anh xác nhận hoặc có bằng chứng.</span></div>}<button className="primary-button" onClick={confirmUsage} disabled={!selected||!currentProjectId}>Xác nhận đã dùng trong project</button></aside>}

function ProjectsView({projects,currentProjectId,setCurrentProjectId,projectName,setProjectName,createProject}:{projects:Project[];currentProjectId?:number;setCurrentProjectId:(id:number)=>void;projectName:string;setProjectName:(value:string)=>void;createProject:()=>void}){const [memories,setMemories]=useState<MemoryEntry[]>([]);useEffect(()=>{window.mh.projects.memories(currentProjectId?{projectId:currentProjectId}:{}).then(setMemories)},[currentProjectId]);return <div className="route-panel"><div className="route-head"><div><span className="eyebrow">Producer context</span><h2>Dự án và trí nhớ sử dụng</h2><p>Preview, kéo sang FL và xác nhận sử dụng là ba sự kiện khác nhau.</p></div><div className="create-inline"><input value={projectName} onChange={event=>setProjectName(event.target.value)} placeholder="Tên project mới"/><button className="primary-button" onClick={createProject}>Tạo project</button></div></div><div className="project-chips">{projects.map(project=><button key={project.id} className={currentProjectId===project.id?"active":""} onClick={()=>setCurrentProjectId(project.id)}><Icon name="project"/><span><b>{project.name}</b><small>{project.bpm?`${project.bpm} BPM · `:""}{project.style||"Chưa gắn style"}</small></span></button>)}</div><div className="memory-table"><div className="memory-row head"><span>Sample</span><span>Project</span><span>Sự kiện</span><span>Nguồn / tin cậy</span><span>Thời gian</span></div>{memories.map(memory=><div className="memory-row" key={memory.id}><span>{memory.sample_name}</span><span>{memory.project_name}</span><span><Badge tone={memory.event_type==="user_confirmed"?"success":"warning"}>{memory.event_type}</Badge></span><span>{memory.source} · {Math.round(memory.confidence*100)}%</span><span>{new Date(memory.occurred_at).toLocaleString("vi-VN")}</span></div>)}</div></div>}
function SafetyView({groups}:{groups:DuplicateGroup[]}){const saved=useMemo(()=>groups.reduce((sum,group)=>sum+(group.total_size-(group.samples[0]?.size_bytes||0)),0),[groups]);return <div className="route-panel"><div className="route-head"><div><span className="eyebrow">Project-Safe Lab</span><h2>Exact duplicate có bằng chứng</h2><p>Đọc và mô phỏng; không xóa, chuyển hoặc hard-link file.</p></div><div className="safe-summary"><b>{groups.length}</b> nhóm · {formatBytes(saved)} có thể xem xét</div></div><div className="duplicate-list">{groups.map(group=><article key={group.exact_hash}><header><Badge tone="success">SHA-256 khớp</Badge><b>{group.file_count} file · {formatBytes(group.total_size)}</b><code>{group.exact_hash.slice(0,20)}…</code></header>{group.samples.map((sample,index)=><div className="duplicate-file" key={sample.id}><Badge tone={index?"neutral":"cyan"}>{index?"Bản trùng":"Ứng viên giữ"}</Badge><span><b>{sample.filename}</b><small>{sample.path}</small></span><em>{formatBytes(sample.size_bytes)}</em></div>)}</article>)}</div>{!groups.length&&<div className="route-empty"><Icon name="safe" size={32}/><b>Chưa có exact duplicate đã xác minh</b><span>Chỉ file có hash đầy đủ mới xuất hiện ở đây.</span></div>}</div>}
function SettingsModal({close,setNotice,resetLayout}:{close:()=>void;setNotice:(message:string)=>void;resetLayout:()=>void}){const [busy,setBusy]=useState(false);const action=async(fn:()=>Promise<string>,label:string)=>{setBusy(true);try{const output=await fn();setNotice(`${label}: ${output}`);close()}finally{setBusy(false)}};return <div className="modal-backdrop" onMouseDown={close}><dialog open className="modal" onMouseDown={event=>event.stopPropagation()}><header><h2>Cài đặt và dữ liệu</h2><button onClick={close}>×</button></header><div className="setting-row"><div><b>Bố cục workspace</b><p>Đặt lại chiều rộng pane, chiều cao và các cột.</p></div><button className="action-button" onClick={()=>{resetLayout();setNotice("Đã đặt lại bố cục mặc định.");close()}}>Đặt lại</button></div><div className="setting-row"><div><b>Sao lưu SQLite</b><p>Tạo bản sao database phục hồi được.</p></div><button className="action-button" disabled={busy} onClick={()=>action(window.mh.settings.backup,"Đã sao lưu")}>Tạo backup</button></div><div className="setting-row"><div><b>Xuất báo cáo JSON</b><p>Bao gồm roots, cây folder, samples, projects và provenance.</p></div><button className="action-button" disabled={busy} onClick={()=>action(window.mh.settings.exportSnapshot,"Đã xuất")}>Xuất dữ liệu</button></div><div className="policy"><Icon name="shield"/><span><b>VST3 đang khóa</b><p>Chỉ mở sau khi ứng dụng desktop được anh nghiệm thu.</p></span></div></dialog></div>}
